/****** Script for calculating the average volume and standard deviation of a given activity for a given diagnosis *****/

SELECT
	[DIAGNOSIS_CODE]
	,[ACTIVITY_CODE]
	,ACTIVITY_COUNT_TOTAL/[DIAGNOSIS_CODE_COUNT] AS ACTIVITY_COUNT_AVG
	,CASE WHEN [DIAGNOSIS_CODE_COUNT]>1 THEN SQRT(([DIAGNOSIS_CODE_COUNT]-ACTIVITY_COUNT_TOTAL)*(ACTIVITY_COUNT_AVG*ACTIVITY_COUNT_AVG)/([DIAGNOSIS_CODE_COUNT]-1)) ELSE 0 END AS ACTIVITY_COUNT_STDEV
	FROM
	(
		SELECT 
			DTC.[DIAGNOSIS_CODE]
			,[ACTIVITY_CODE]
			,CAST (COUNT(*)  AS FLOAT) AS ACTIVITY_COUNT_TOTAL
			,CAST ([DIAGNOSIS_CODE_COUNT] AS FLOAT) [DIAGNOSIS_CODE_COUNT]
			,CAST(COUNT(*) AS FLOAT)/CAST([DIAGNOSIS_CODE_COUNT] AS FLOAT) AS ACTIVITY_COUNT_AVG	
		FROM [ANALYTICS].[DBO].[DTC]
		JOIN [ANALYTICS].[DBO].CA ON [DTC].DTC_KEY=CA.DTC_KEY
		JOIN (
			SELECT 
				[DIAGNOSIS_CODE]
				,COUNT(*) AS [DIAGNOSIS_CODE_COUNT]
			FROM [ANALYTICS].[DBO].[DTC]
			JOIN [ANALYTICS].[DBO].CA ON [DTC].DTC_KEY=CA.DTC_KEY
			WHERE [DIAGNOSIS_CODE] <> ''
			GROUP BY [DIAGNOSIS_CODE]
			) A 
		ON DTC.DIAGNOSIS_CODE=A.DIAGNOSIS_CODE
		WHERE DTC.[DIAGNOSIS_CODE] <> ''
		GROUP BY 
			DTC.[DIAGNOSIS_CODE]
			,[ACTIVITY_CODE]
			,[DIAGNOSIS_CODE_COUNT]		
) R
